version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sagequery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  # Pinecone is a managed service; for local dev, use pgvector or document Pinecone cloud setup
volumes:
  pgdata: 